server:
  port: 9020

spring:
  application:
    name: MS-deal

  datasource:
    url: jdbc:postgresql://localhost:5432/credit_services
    username: neoflex_admin
    password: qadminwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

external:
  calculator:
    base-url: http://localhost:9010
    offers-path: /calculator/offers
    calc-path: /calculator/calc

docs:
  title: Deal Microservice
  version: 0.8.0
  description: |
    This microservice handles the deal management for the credit services.
    It includes functionalities for creating, updating, and retrieving deals.

kafka:
  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    statement-denied: statement-denied

email:
  templates:
    finish-registration: "Пожалуйста, завершите регистрацию для получения кредита."
    create-documents: "Ваши документы успешно сформированы."
    send-documents: "Документы были отправлены на вашу почту."
    send-ses: "Пожалуйста, подпишите документы через электронную подпись. Ваш код: %s"
    credit-issued: "Поздравляем! Кредит был успешно выдан."
    statement-denied: "К сожалению, ваша заявка на кредит была отклонена."