server:
  port: 9030

spring:
  application:
    name: MS-statement

external:
  deal:
    base-url: http://ms-deal:9020
    statement-path: /deal/statement
    offer-path: /deal/offer/select

docs:
  title: Statement Microservice
  version: 0.8.0
  description: |
    This microservice is responsible for prescoring and requests to the deal microservice.